### ISSUE TITLE
[20w19a] java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Yoghurt4C** [Szum123321/textile_backup#11]
Exception in thread "Thread-132" java.lang.NoSuchMethodError: net/minecraft/class_3218.method_17982()Lnet/minecraft/class_29; (loaded from file:/C:/Users/yoghu_000/Desktop/modding%20shit/MultiMC/instances/experimental_snapsnot_server/.minecraft/.fabric/remappedJars/minecraft-1.16-alpha.20.19.a/intermediary-minecraft-20w19a-client.jar by net.fabricmc.loader.launch.knot.KnotClassLoader@9e9d70e9) called from class net.szum123321.textile_backup.core.MakeBackupThread (loaded from file:/C:/Users/yoghu_000/Desktop/modding%20shit/MultiMC/instances/experimental_snapsnot_server/.minecraft/mods/textile_backup-1.2.0-1.16.jar by net.fabricmc.loader.launch.knot.KnotClassLoader@9e9d70e9).
	at net.szum123321.textile_backup.core.MakeBackupThread.run(MakeBackupThread.java:51)
	at java.lang.Thread.run(Thread.java:813)

**Comment by Szum123321** [comment]
Quite some stuff changed in 20w19a, so that was expected. I won't rush this update because there is not much point in it. Repaired version should be available in few day.

**Comment by Szum123321** [comment]
Fixed in commit 7e1fe5a6020b897acdba0d3660d061fad66f354f
