### ISSUE TITLE
Backups not works with C2ME mod

### ISSUE THREAD

**Issue by diskria** [Szum123321/textile_backup#133]
Auto backup is not working in single player (works only backups when shutdown). It's just not send "Done!" message and folder is missing. 
Configs: Default
I use this mod in my mod pack, [included mods here](https://modrinth.com/modpack/achievetodo#:~:text=%F0%9F%93%A6-,Resources,-Mods
):
![javaw_7KLAq8CJw3](https://github.com/Szum123321/textile_backup/assets/96978370/242d595c-126a-4043-96ac-e6997094f845)

Logs:

```
[19:04:21] [Server thread/INFO]: [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[19:04:21] [Server thread/INFO]: [Textile Backup] Backup started by: Timer on: 2023.07.23_19-04-21
[19:04:21] [pool-5-thread-1/INFO]: [Textile Backup] Saving server...
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$baa000$c2me-fixes-general-threading-issues$preventAsyncSaveAll(MinecraftServer.java:6819)
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java)
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at net.szum123321.textile_backup.core.create.ExecutableBackup.call(ExecutableBackup.java:69)
[19:04:21] [Render thread/INFO]: [System] [CHAT] [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at net.szum123321.textile_backup.core.create.ExecutableBackup.call(ExecutableBackup.java:25)
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:04:21] [pool-5-thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by diskria** [comment]
Damn, I just found it myself, there seems to be a conflict with the C2ME mod

UPD: Yes, it is problem with C2ME

**Comment by diskria** [comment]
https://github.com/RelativityMC/C2ME-fabric/issues/228

**Comment by diskria** [comment]
According to [this C2ME mixin](https://github.com/RelativityMC/C2ME-fabric/commit/58b48760199413e64bb2f5301ffe9461404df505#diff-e665912cd194d211fefbf1f89147614cb1152d2ea7056dd052194a04c4ce7e9dR27), we need to execute the world save in the server thread

**Comment by Szum123321** [comment]
please move the discussion to #123
