### ISSUE TITLE
Crash when making a backup

### ISSUE THREAD

**Issue by DuendeInexistente** [Szum123321/textile_backup#137]
Getting a fatal crash when a backup runs in my world, possibly because I've been exploring and the world size increased significantly. Playing with Fabulously Optimized and a few other QoL mods, with the latest version of minecraft and Textile Backup.
[Log.](https://paste.ee/p/YjcLj)

**Comment by zhenruyan** [comment]
+1 1.20.1

Excessive IO and memory usage, leading to an entire system explosion

**Comment by amot-dev** [comment]
My backup is also crashing, I assume for the same/similar reasons? I've attached the relevant part of my log:
```
[12:34:32] [Server thread/INFO]: [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[12:34:32] [Server thread/INFO]: [Textile Backup] Backup started by: Timer on: 2023.09.01_12-34-32
[12:34:32] [pool-3-thread-1/INFO]: [Textile Backup] Saving server...
[12:34:32] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[?:?]
	at net.minecraft.class_3204.method_15892(class_3204.java:127) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_16155(class_3215.java:286) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:569) ~[server-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbf000$carpet$modifiedRunLoop(MinecraftServer.java:6451) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:34:32] [Server thread/ERROR]: This crash report has been saved to: /mnt/g/Minecraft/Server/Grace/./crash-reports/crash-2023-09-01_12.34.32-server.txt
[12:34:32] [Server thread/INFO]: Stopping server
[12:34:32] [Server thread/INFO]: Saving players
[12:34:32] [Server thread/INFO]: asd1o1 lost connection: Server closed
[12:34:32] [Server thread/INFO]: asd1o1 left the game
[12:34:32] [Server thread/INFO]: Saving worlds
[12:34:32] [pool-3-thread-1/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:34:32] [pool-3-thread-1/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:34:32] [pool-3-thread-1/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:34:32] [pool-3-thread-1/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:34:32] [pool-3-thread-1/INFO]: [Textile Backup] Starting backup
[12:34:41] [pool-3-thread-1/INFO]: [Textile Backup] Compression took: 08.965 seconds.
[12:34:41] [pool-3-thread-1/INFO]: [Textile Backup] Deleted: /mnt/g/Minecraft/Server/Grace/backup/world/2023.08.23_10-35-40#shutdown.zip
[12:34:41] [pool-3-thread-1/INFO]: [Textile Backup] Done!
[12:34:41] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[12:34:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[12:34:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[12:34:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[12:34:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[12:34:42] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[12:34:42] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[12:34:42] [Server thread/INFO]: [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[12:34:42] [Server thread/INFO]: [Textile Backup] Backup started by: Server Shutdown on: 2023.09.01_12-34-42
[12:34:42] [Server thread/INFO]: [Textile Backup] Starting backup
[12:34:51] [Server thread/INFO]: [Textile Backup] Compression took: 09.082 seconds.
[12:34:51] [Server thread/INFO]: [Textile Backup] Deleted: /mnt/g/Minecraft/Server/Grace/backup/world/2023.08.26_15-18-35.zip
[12:34:51] [Server thread/INFO]: [Textile Backup] Done!
```
And here is the crash report: [crash-2023-09-01_12.34.32-server.txt](https://github.com/Szum123321/textile_backup/files/12501153/crash-2023-09-01_12.34.32-server.txt)

**Comment by Szum123321** [comment]
Related to  #123. Please move all discussion there.
