### ISSUE TITLE
Textile backup 3.1.2-1.19 incompatible with Minecraft 1.19.2

### ISSUE THREAD

**Issue by mirai-toto** [Szum123321/textile_backup#145]
I use Modrinth to create my modpack on **Minecraft 1.19.2**, but when I launch my modpack I get the error:

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Textile Backup' (textile_backup) 3.1.2-1.19 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Textile Backup' (textile_backup) 3.1.2-1.19 requires any version between 1.20- (inclusive) and 2- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Downgrading to Textile Backup 2.5.0-1.19 make it works. But I may have misuderstood the situation, because I thought the Textile Backup 3.1.2 supports **Minecraft 1.19**

**Comment by Szum123321** [comment]
Oh yeah. Repaired
