### ISSUE TITLE
A stderr with textile

### ISSUE THREAD

**Issue by Dan-k391** [Szum123321/textile_backup#151]
```
[20:12:39] [pool-6-thread-1/INFO]: [Textile Backup] Saving server...
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]: java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at net.minecraft.server.MinecraftServer.handler$zzj000$c2me-fixes-general-threading-issues$preventAsyncSaveAll(MinecraftServer.java:8319)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at net.szum123321.textile_backup.core.create.ExecutableBackup.call(ExecutableBackup.java:69)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at net.szum123321.textile_backup.core.create.ExecutableBackup.call(ExecutableBackup.java:25)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[20:12:39] [pool-6-thread-1/INFO]: [STDERR]:    at java.base/java.lang.Thread.run(Thread.java:1583)
```

I just downloaded the mod and tried /backup start ~~~ and nothing happened. 
This is the log

**Comment by Szum123321** [comment]
Which TxB and Minecraft version are you running?

**Comment by Szum123321** [comment]
Closing due to inactivity
