### ISSUE TITLE
Unable to create Backup file while server is online (Version:1.20.1)

### ISSUE THREAD

**Issue by ReimuKKSK** [Szum123321/textile_backup#160]
Mod version : 3.1.0-1.20
Fabric version : 0.15.9
Minecraft version : 1.20.1

Well, the mod is able to create a backup world file when the server is shutting down
But, it can't create any file while the server is online either Auto backup or manually /backup

Error massage while the mod is trying to backup : 
[01:07:37] [Server thread/INFO]: [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[01:07:37] [Server thread/INFO]: [Textile Backup] Backup started by: Timer on: 2024.07.09_01-07-37
[01:07:37] [pool-7-thread-1/INFO]: [Textile Backup] Saving server...
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: java.util.ConcurrentModificationException: Attempted to call MinecraftServer#saveAll async
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$zzj000$c2me-fixes-general-threading-issues$preventAsyncSaveAll(MinecraftServer.java:11819)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at net.szum123321.textile_backup.core.create.ExecutableBackup.call(ExecutableBackup.java:69)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at net.szum123321.textile_backup.core.create.ExecutableBackup.call(ExecutableBackup.java:25)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[01:07:37] [pool-7-thread-1/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by Szum123321** [comment]
U
