### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by notSalt** [Szum123321/textile_backup#32]
This happened when attempting to use `/backup cleanup` command
```
java.lang.NoSuchMethodError: java.util.stream.Stream.takeWhile(Ljava/util/function/Predicate;)Ljava/util/stream/Stream;
	at net.szum123321.textile_backup.core.BackupHelper.executeFileLimit(BackupHelper.java:85)
	at net.szum123321.textile_backup.commands.CleanupCommand.execute(CleanupCommand.java:34)
	at net.szum123321.textile_backup.commands.CleanupCommand.lambda$register$0(CleanupCommand.java:30)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
	at net.minecraft.class_2170.method_9249(class_2170.java:260)
	at net.minecraft.class_3244.method_14370(class_3244.java:1134)
	at net.minecraft.class_3244.method_12048(class_3244.java:1121)
	at net.minecraft.class_2797.method_12115(class_2797.java:36)
	at net.minecraft.class_2797.method_11054(class_2797.java:9)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:763)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:154)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:745)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:739)
	at net.minecraft.class_1255.method_5383(class_1255.java:103)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:723)
	at net.minecraft.server.MinecraftServer.handler$zil000$modifiedRunLoop(MinecraftServer.java:3805)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:653)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Szum123321** [comment]
Does normal backup routine work?

**Comment by notSalt** [comment]
Had same issue as #31 but switching to GZIP fixed it so normal backup works fine.

**Comment by Szum123321** [comment]
That's completely different problem and changing compression method worked only by pure luck.

More pernament solution would be to update java.

**Comment by Szum123321** [comment]
Ok, so this mod uses some Java 9+ features and it might be possible that this causes some problem on java 8 mashine. I'm working on more Java 8-friendly version that will be available soon.

**Comment by Szum123321** [comment]
Should be repaired in 1.4.0. If the problem still persists after update, please reopen this issue.
