### ISSUE TITLE
Out of space error when there is enough space

### ISSUE THREAD

**Issue by Glucy-2** [Szum123321/textile_backup#51]
I'm running a minecraft server on Pterodactyl Software.
When I tried to start backup using ZIP, it occurs an error, and I get an 53B file, but if I use GZIP I can get a backup.
I tried release 2.1.0 and 2.0.1 and get the same error.
I have 10000MB of space and 4868MB used.
Here is the server log and the config file: 
- server log
````python
backup start
[09:16:07] [Server thread/INFO]: [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[09:16:07] [Server thread/INFO]: [Textile Backup] Backup started from: Server Console on: 2020-12-13_09-16-07
[09:16:07] [Server thread/INFO]: [Textile Backup] Saving server...
[09:16:07] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[09:16:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[09:16:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[09:16:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[09:16:08] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[09:16:08] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[09:16:08] [pool-3-thread-1/INFO]: [Textile Backup] Starting backup
[09:16:10] [pool-3-thread-1/ERROR]: [Textile Backup] An exception occurred!
java.util.concurrent.ExecutionException: java.io.IOException: No space left on device
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator.writeTo(ParallelScatterZipCreator.java:266) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at net.szum123321.textile_backup.core.create.compressors.ParallelZipCompressor.finish(ParallelZipCompressor.java:71) ~[%5B%E5%A4%87%E4%BB%BD%5Dtextile_backup-2.1.0-prev-1.16.4.jar:?]
at net.szum123321.textile_backup.core.create.compressors.AbstractCompressor.createArchive(AbstractCompressor.java:56) [%5B%E5%A4%87%E4%BB%BD%5Dtextile_backup-2.1.0-prev-1.16.4.jar:?]
at net.szum123321.textile_backup.core.create.MakeBackupRunnable.run(MakeBackupRunnable.java:86) [%5B%E5%A4%87%E4%BB%BD%5Dtextile_backup-2.1.0-prev-1.16.4.jar:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.io.IOException: No space left on device
at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_275]
at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[?:1.8.0_275]
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_275]
at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_275]
at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[?:1.8.0_275]
at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_275]
at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_275]
at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_275]
at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_275]
at org.apache.commons.compress.parallel.FileBasedScatterGatherBackingStore.writeOut(FileBasedScatterGatherBackingStore.java:65) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor$ScatterGatherBackingStoreCompressor.writeOut(StreamCompressor.java:291) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:273) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate(StreamCompressor.java:264) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor.deflateUntilInputIsNeeded(StreamCompressor.java:257) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor.writeDeflated(StreamCompressor.java:238) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor.write(StreamCompressor.java:205) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate(StreamCompressor.java:184) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry(ScatterZipOutputStream.java:100) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$3.call(ParallelScatterZipCreator.java:210) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$3.call(ParallelScatterZipCreator.java:206) ~[efb869e4-8c45-477e-ae63-12b07da14b37.jar:?]
... 4 more
[09:16:10] [pool-3-thread-1/INFO]: [Textile Backup] Compression took: 01.763 seconds.
[09:16:10] [pool-3-thread-1/INFO]: [Textile Backup] Done!
````
- config
````json5
{
	/* 
	   Time between automatic backups in seconds
	   When set to 0 backups will not be performed automatically
	*/
	"backupInterval": 864000,
	/* 
	   Delay in seconds between typing-in /backup restore and it actually starting
	*/
	"restoreDelay": 30,
	/* 
	   Should backups be done even if there are no players?
	*/
	"doBackupsOnEmptyServer": false,
	/* 
	   Should backup be made on server shutdown?
	*/
	"shutdownBackup": true,
	/* 
	   Should world be backed up before restoring a backup?
	*/
	"backupOldWorlds": false,
	/* 
	   Should every world have its own backup folder?
	*/
	"perWorldBackup": false,
	/* 
	   A path to the backup folder
	*/
	"path": "/home/container/backup",
	/* 
	   This setting allows you to exclude files form being backedup.
	   Be very careful when setting it, as it is easy corrupt your world!
	*/
	"fileBlacklist": [],
	/* 
	   Should backups be deleted after being restored?
	*/
	"deleteOldBackupAfterRestore": true,
	/* 
	   Maximum number of backups to keep. If set to 0 then no backup will be deleted based their amount
	*/
	"backupsToKeep": 20,
	/* 
	   Maximum age of backups to keep in seconds.
	    If set to 0 then backups will not be deleted based their age 
	*/
	"maxAge": 1382400,
	/* 
	   Maximum size of backup folder in kilo bytes (1024).
	   If set to 0 then backups will not be deleted
	*/
	"maxSize": 10485760,
	/* 
	   Compression level 
	   0 - 9
	    Only affects zip compression.
	*/
	"compression": 9,
	/* 
	   Limit how many cores can be used for compression.
	   0 means that all available cores will be used
	*/
	"compressionCoreCountLimit": 0,
	/* 
	   Available formats are:
	   ZIP - normal zip archive using standard deflate compression
	   GZIP - tar.gz using gzip compression
	   BZIP2 - tar.bz2 archive using bzip2 compression
	   LZMA - tar.xz using lzma compression
	*/
	"format": "ZIP",
	/* 
	   Minimal permission level required to run commands
	*/
	"permissionLevel": 0,
	/* 
	   Player on singleplayer is always allowed to run command. Warning! On lan party everyone will be allowed to run it.
	*/
	"alwaysSingleplayerAllowed": true,
	/* 
	   Players allowed to run backup commands without sufficient permission level
	*/
	"playerWhitelist": [],
	/* 
	   Players banned from running backup commands besides their sufficient permission level
	*/
	"playerBlacklist": [],
	/* 
	   Format of date&time used to name backup files.
	   Remember not to use '#' symbol or any other character that is not allowed by your operating system such as:
	   ':', '\', etc...
	   For more info: https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html
	*/
	"dateTimeFormat": "yyyy-MM-dd_HH-mm-ss"
}
````

**Comment by Szum123321** [comment]
Oh snap! I thought it was finally gone! For now try setting `compressionCoreCountLimit` to 1, that way a more typical zip compressor will be used. 

Also, thank you for telling me about the Pterodactyl Software. That's probably what causes all the issues.

**Comment by mrspinn** [comment]
@Szum123321 any other suggestions? I tried setting the `compressionCoreCountLimit` to 1 but I'm still getting that same error as above.

**Comment by GeneralCyber1** [comment]
Can confirm I'm still having this issue even after setting compressioncorecountlimit to 1. Also using Pterodactyl Software though

**Comment by MSandro** [comment]
setting compressionCoreCountLimit to 1 did not work for me, and I am not using Pterodactyl.
But I've changed the Format to GZIP and now it works again
