### ISSUE TITLE
Restored backup is being deleted

### ISSUE THREAD

**Issue by j0r1s** [Szum123321/textile_backup#52]
Scenario : 
- I have option `backupsToKeep: 3`
- I start restoring my oldest backup with `/backup restore <timestamp>`
- When server is being shutdown a new backup is created and the one that I wanted restored is deleted
- Then an error is thrown since it can't find the zip backup to restore

```bash
[11:51:00] [Thread-69/INFO]: [Textile Backup] Backup started because of: Backup Restoration on: 13.12.2020_11-51-00
[11:51:00] [Thread-69/INFO]: Starting backup
[11:51:00] [Thread-69/INFO]: [Textile Backup] Starting backup
[11:51:00] [Thread-69/INFO]: Starting compression...
[11:51:00] [Thread-69/INFO]: Compression took: 00.164 seconds.
[11:51:00] [Thread-69/INFO]: Deleting: 12.12.2020_12-30-08#shutdown.zip
[11:51:00] [Thread-69/INFO]: [Textile Backup] Deleting: 12.12.2020_12-30-08#shutdown.zip
[11:51:00] [Thread-69/INFO]: Done!
[11:51:00] [Thread-69/INFO]: [Textile Backup] Done!
[11:51:00] [Thread-69/INFO]: [Textile Backup] Deleting old world...
[11:51:00] [Thread-69/INFO]: [Textile Backup] Starting decompression...
[11:51:00] [Thread-69/ERROR]: [Textile Backup] An exception occurred!
java.io.FileNotFoundException: /home/minecraft/server/backup/world/12.12.2020_12-30-08#shutdown.zip (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[?:?]
        at java.io.FileInputStream.open(FileInputStream.java:219) ~[?:?]
        at java.io.FileInputStream.<init>(FileInputStream.java:157) ~[?:?]
        at net.szum123321.textile_backup.core.restore.decompressors.ZipDecompressor.decompress(ZipDecompressor.java:36) [textile_backup-2.0.2-1.16.3.jar:?]
        at net.szum123321.textile_backup.core.restore.RestoreBackupRunnable.run(RestoreBackupRunnable.java:72) [textile_backup-2.0.2-1.16.3.jar:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[11:51:00] [Thread-69/INFO]: [Textile Backup] Decompression took: 00.002 seconds.
[11:51:00] [Thread-69/INFO]: [Textile Backup] Deleting old backup
[11:51:00] [Thread-69/INFO]: [Textile Backup] Something went wrong while deleting old backup
[11:51:00] [Thread-69/INFO]: [Textile Backup] Done!
```

Let me know if I can provide any further help.

**Comment by Szum123321** [comment]
Are you using the 2.1.0-prev verison?

**Comment by Szum123321** [comment]
Right, thank you for reporting this bug. I was comparing file objects instead of their path. Here's a repaired version (zipped because github doesn't allow uploading jars) [textile_backup-2.1.0-prev2-1.16.4.jar.zip](https://github.com/Szum123321/textile_backup/files/5684517/textile_backup-2.1.0-prev2-1.16.4.jar.zip)
