### ISSUE TITLE
Bug: Compression

### ISSUE THREAD

**Issue by ElijahRus250** [Szum123321/textile_backup#55]
```backup start
[17:10:20] [Server thread/INFO]: [Textile Backup] Warning! Server backup will begin shortly. You may experience some lag.
[17:10:20] [Server thread/INFO]: [Textile Backup] Backup started from: Server Console on: 2021.01.07_17-10-20
[17:10:20] [Server thread/INFO]: [Textile Backup] Saving server...
[17:10:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[17:10:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[17:10:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[17:10:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[17:10:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[17:10:25] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[17:10:25] [pool-3-thread-1/INFO]: [Textile Backup] Starting backup
[17:10:25] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4851ms or 97 ticks behind
[17:10:26] [Server thread/WARN]: Hoax01 moved too quickly! -0.37123673207111096,0.0,-10.196248866896894
[17:10:27] [pool-3-thread-1/ERROR]: [Textile Backup] An exception occurred!
java.util.concurrent.ExecutionException: java.io.IOException: No space left on device
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
        at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator.writeTo(ParallelScatterZipCreator.java:266) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at net.szum123321.textile_backup.core.create.compressors.ParallelZipCompressor.finish(ParallelZipCompressor.java:71) ~[textile_backup-2.1.0-prev-1.16.4.jar:?]
        at net.szum123321.textile_backup.core.create.compressors.AbstractCompressor.createArchive(AbstractCompressor.java:56) [textile_backup-2.1.0-prev-1.16.4.jar:?]
        at net.szum123321.textile_backup.core.create.MakeBackupRunnable.run(MakeBackupRunnable.java:86) [textile_backup-2.1.0-prev-1.16.4.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_275]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.io.IOException: No space left on device
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method) ~[?:1.8.0_275]
        at sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:60) ~[?:1.8.0_275]
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93) ~[?:1.8.0_275]
        at sun.nio.ch.IOUtil.write(IOUtil.java:65) ~[?:1.8.0_275]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:211) ~[?:1.8.0_275]
        at java.nio.channels.Channels.writeFullyImpl(Channels.java:78) ~[?:1.8.0_275]
        at java.nio.channels.Channels.writeFully(Channels.java:101) ~[?:1.8.0_275]
        at java.nio.channels.Channels.access$000(Channels.java:61) ~[?:1.8.0_275]
        at java.nio.channels.Channels$1.write(Channels.java:174) ~[?:1.8.0_275]
        at org.apache.commons.compress.parallel.FileBasedScatterGatherBackingStore.writeOut(FileBasedScatterGatherBackingStore.java:65) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor$ScatterGatherBackingStoreCompressor.writeOut(StreamCompressor.java:291) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor.writeCounted(StreamCompressor.java:273) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate(StreamCompressor.java:264) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor.deflateUntilInputIsNeeded(StreamCompressor.java:257) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor.writeDeflated(StreamCompressor.java:238) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor.write(StreamCompressor.java:205) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.StreamCompressor.deflate(StreamCompressor.java:184) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.ScatterZipOutputStream.addArchiveEntry(ScatterZipOutputStream.java:100) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$3.call(ParallelScatterZipCreator.java:210) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        at org.apache.commons.compress.archivers.zip.ParallelScatterZipCreator$3.call(ParallelScatterZipCreator.java:206) ~[f61c70f6-f9de-44af-a874-53bda4f47544.jar:?]
        ... 4 more
[17:10:27] [pool-3-thread-1/INFO]: [Textile Backup] Compression took: 01.960 seconds.
[17:10:27] [pool-3-thread-1/INFO]: [Textile Backup] Deleting: 2021.01.07_00-25-34.zip
[17:10:27] [pool-3-thread-1/INFO]: [Textile Backup] Done!```

**Comment by Szum123321** [comment]
This is sadly a [known issue](https://github.com/Szum123321/textile_backup/wiki/ZIP-Problems) <- see for solutions.

Could you please tell me where's your server running? (a hosting site, if so then which?). That would really help me to get this issue finally resolved. Thanks!

**Comment by ElijahRus250** [comment]
Hey there, I am using https://dedicatedmc.io and there budget plan.

**Comment by Szum123321** [comment]
Thank you!
